crailnative: move our warpper class from gg to crailnative 1. we can't include header which contains template class or function when compile in different pass. 2. set -D_GLIBCXX_USE_CXX11_ABI to 1, or we will have a link issue due to .symtab mismatch
/usr/bin/ld: /home/dengxh/Desktop/gg/src/net/crail.cc:96: undefined reference to `CrailClient::Get(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&)'
/usr/bin/ld: ../net/libggnet.a(crail.o): in function `Crail::upload_files(std::vector<storage::PutRequest, std::allocator<storage::PutRequest> > const&, std::function<void (storage::PutRequest const&)> const&)':
/home/dengxh/Desktop/gg/src/net/crail.cc:28: undefined reference to `CrailClient::CrailClient(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, unsigned short)'
/usr/bin/ld: /home/dengxh/Desktop/gg/src/net/crail.cc:54: undefined reference to `CrailClient::Set(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
collect2: error: ld returned 1 exit status